### ISSUE TITLE
transfer of closed pr from pysal-meta

### ISSUE THREAD

**Issue by sjsrey** [pysal/spreg#19]
https://github.com/pysal/pysal/pull/1055

**Comment by ljwolf** [comment]
We would need to sift through these more to figure out what is still needed, but my recollection is that @pedrovma  and I worked pretty closely together to get all this stuff in already to the current spreg release. It appears only 2 things are missing, and only 1 of these is substantive (the `spdot` in the concentrated log likelihoods):

- [X] the init has the `sur` imports ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-beef0d953b18ca9ac12c237c99a46ec5), [here](https://github.com/pysal/spreg/blob/master/spreg/__init__.py))
- [ ] **The `chisqprob` deprecation  fix was removed** ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-575101dc26052066867e97b5642d6b59L9), [here](https://github.com/pysal/spreg/blob/master/spreg/diagnostics.py#L8)) somehow when it came here. I've read that `chisqprob` [was removed](https://docs.scipy.org/doc/scipy-1.2.1/reference/release.1.0.0.html?highlight=chisqprob#backwards-incompatible-changes), but I am still able to run `from scipy.stats import chisqprob` on version 1.2.1 of scipy, so I'm not sure what's up. A deprecation fix for this *was* retained in `diagnostics_sp.py`, ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-925d0ffdd0479977d9a8132f87f6e58dL8), [here](https://github.com/pysal/spreg/blob/master/spreg/diagnostics_sp.py#L10))
- [X] Changes to `diagnostics_sur.py` appear to be applied correctly. ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-4a72b9fc2aaa4743ccac4f944a0fc7ecR142), [here](https://github.com/pysal/spreg/blob/master/spreg/diagnostics_sur.py#L141))
- [X] The removal of the extra `regime_err_sep` is done ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-b329c50e380f0281e24a1265d07403e9L309), [here](https://github.com/pysal/spreg/blob/master/spreg/error_sp_het_regimes.py#L309)).
- [ ] **Changes to the concentrated log likelihood remain undone** ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-3e506ad854bd728cadeacea5e7b61e54L495), [here](https://github.com/pysal/spreg/blob/master/spreg/ml_error.py#L489)).  
- [X] Regimes patch was applied. ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-625d648feda41d35bfa009f528d0ef82L101), [here](https://github.com/pysal/spreg/blob/master/spreg/regimes.py#L79))
- [X] Spatial diagnostics for ML models is enforced. ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-2e754f991b8d7c6307ebb777641e73e3L214), [here](https://github.com/pysal/spreg/blob/master/spreg/summary_output.py#L209)), as well as later changes to the `SUR` summary ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-2e754f991b8d7c6307ebb777641e73e3R648), [here](https://github.com/pysal/spreg/blob/master/spreg/summary_output.py#L649))
- [X] Changes to `sur_lag.py` look applied. ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-3f3c74d24b1665c69fbcb3a6c11f5ad9R211), [here](https://github.com/pysal/spreg/blob/master/spreg/sur_lag.py#L210)), as well as to `sur.py` ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-14edb109bb7cdcb1f08b87a55e0523fbR112), [here](https://github.com/pysal/spreg/blob/master/spreg/sur.py#L112)), `sur_error.py` ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-f570f17b272aeb70a9d135dd23233a57R32), [here](https://github.com/pysal/spreg/blob/master/spreg/sur_error.py#L32)) and `sur_utils.py` ([upstream](https://github.com/pysal/pysal/pull/1055/files#diff-c0c4d8f167e91fae70778c9ef3cc27deR322), [here](https://github.com/pysal/spreg/blob/master/spreg/sur_utils.py#L382))

The remaining changes appear to *not* be things we need (e.g. [referring to `pysal.spreg` as `econometrics`](https://github.com/pysal/pysal/pull/1055/files#diff-337111788b595a2aeeab4639672f64b7R4)), and changes to testing that have been merged, or changes to documentation that [we decided together not to merge](https://github.com/pysal/pysal/pull/1055/files#diff-60e9f19791ad7aadabf4c51427935f61L509).
